name: gg
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 
  firebase_auth: 
  firebase_storage:
  firebase_messaging: ^2.1.0
  flutter_local_notifications:
  sortedmap: ^0.4.2
  cached_network_image:
  video_player:
  chewie:
  numberpicker: ^0.1.7
  http: ^0.11.0
  image_picker:
  gradient_text: ^1.0.2
  auto_size_text: ^0.3.0
  rxdart: ^0.20.0
  intl: ">=0.14.0"
  flutter_masked_text: ^0.7.0
  google_sign_in: ^4.0.1+1
 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.1.0-dev.5.0 <3.0.0"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/background.png
    - assets/gglogo.png
    - assets/googleIcon.png
    - assets/allIcon.png
    - assets/playstationIcon.png
    - assets/xboxIcon.png
    - assets/pcIcon.png
    - assets/switchIcon.png
    - assets/globalIcon.png
    - assets/default/default0.png
    - assets/default/default1.png
    - assets/default/default2.png
    - assets/default/default3.png
    - assets/default/default4.png
    - assets/default/default5.png
    - assets/default/default6.png
    - assets/default/default7.png
    - assets/default/default8.png
    - assets/default/default9.png
    - assets/default/default10.png
    - assets/default/default11.png
    - assets/default/default12.png
    - assets/default/default13.png
    - assets/default/default14.png
    - assets/default/default15.png
    - assets/default/default16.png
    - assets/default/default17.png
    - assets/default/default18.png
    - assets/default/default19.png
    - assets/default/default20.png
    - assets/default/default21.png
    - assets/default/default22.png
    - assets/default/default23.png
    - assets/default/default24.png
    - assets/default/default25.png
    - assets/default/default26.png
    - assets/default/default27.png
    - assets/default/default28.png
    - assets/default/default29.png
    - assets/default/default30.png
    - assets/default/default31.png
    - assets/default/default32.png
    - assets/default/default33.png
    - assets/default/default34.png
    - assets/default/default35.png
    - assets/default/default36.png
    - assets/default/default37.png
    - assets/theme/theme0.png
    - assets/theme/theme1.png
    - assets/theme/theme2.png
    - assets/theme/theme3.png
    - assets/theme/theme4.png
    - assets/theme/theme5.png
    - assets/theme/theme6.png
    - assets/theme/theme7.png
    - assets/theme/theme8.png




  fonts: 
    - family: Century Gothic
      fonts:
        - asset: fonts/centurygothicfont.ttf
        - asset: fonts/centurygothicboldfont.ttf
          weight: 700 
    - family: Trophy
      fonts:
        - asset: icons/trophy.ttf
    - family: Profile
      fonts:
        - asset: icons/profile.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages